collections_config:
  charging:
    path: _charging
    name: Charging Sessions
    icon: ev_station
    create:
      extra_data:
        filename: '{date|year}-{date|month}-{date|day}'
      path: '[relative_base_path]/{filename}[count].md'
    schemas:
      default:
        path: .cloudcannon/schemas/charging.md
    _editables:
      content: false
    add_options:
      - name: Add Charging Session
        schema: default

_inputs:
  date:
    type: date
    options:
      time_format: false
      timezone: America/New_York
  location:
    type: select
    options:
      values:
        - Home
        - Work
        - "Tesla, Lansing"
        - "Tesla, Ohio"
        - "Tesla, Battle Creek"
        - "Tesla, Stevensville, MI"
        - "Tesla, Des Plains, IL"
        - "ChargePoint, Muskegon"
        - "ChargePoint, Clare, MI"
        - "ChargePoint, Grand Rapids, MI"
        - "ChargePoint, DIA, Detroit"
        - "Rivian, Clare, MI"
        - "MGM Grand, Detroit, MI"
        - "Blink, BJ's Wholesale, Canton"
        - "Paul & Carol's, Beulah, MI"
  energy_kwh:
    type: number
    comment: "Energy added in kWh"
  cost:
    type: number
    comment: "Total cost in USD"
  notes:
    type: textarea